# Generated by Django 4.2 on 2023-06-03 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento_Identidad',
            fields=[
                ('tipo_documento_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tipo_documento_nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Tipo_Documento_Identidad',
            },
        ),
        migrations.CreateModel(
            name='tipos_seguro',
            fields=[
                ('tipo_seguro_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('tipo_seguro_nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'tipos_seguro',
            },
        ),
    ]
