# Generated by Django 4.2 on 2023-06-03 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctores',
            fields=[
                ('doctor_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('doctor_nombre', models.CharField(max_length=100)),
                ('doctor_direccion', models.CharField(max_length=100)),
                ('doctor_telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='especialidades',
            fields=[
                ('especialidad_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('especialidad_nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='citas_medicas',
            fields=[
                ('cita_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('observaciones', models.CharField(max_length=250)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctores')),
                ('especialidad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.especialidades')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paciente')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
